# Site
repository: gmtiddia/gmtiddia.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Gianmarco Tiddia
title: PhD student
email: gianmarco.tiddia@dsf.unica.it
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  gmtiddia
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: gianmarco-tiddia
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0001-7524-0285

# Additional icon links
additional_links:
- title: ResearchGate
  icon: fab fa-researchgate
  url: https://www.researchgate.net/profile/Gianmarco-Tiddia
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Gianmarco and I'm a PhD student in Physics at the University of Cagliari!

  My research interests include the study of the neuronal dynamcis of biological neural networks through spiking neural network simulations and mean-field approaches. In particular, I'm interested in understanding the relation between low-level synaptic mechanisms (like short-term plasticity and structural plasticity) and high-level cognitive processes, such as working memory and learning.
  I contribute to the GPU-based spiking network simulator NEST GPU, implementing several network models, curating the documentation and validating the statistical measures of the neural activity against the well-known simulator NEST.  

  
content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: PhD in Physics
        caption: 2020 - present
        sub_title: University of Cagliari
        description: | 
            Thesis title: "Large-scale neuronal networks: from simulation technology to the study of plasticity-driven cognitive processes" [link](https://zenodo.org/doi/10.5281/zenodo.10245798).

      - layout: left
        title: Research Stay
        caption: 21 September 2022 - 28 March 2023
        sub_title: Forschungszentrum Jülich
        description: Research stay at INM-6, in the group of Computational Neurophysics, as part of the PhD program.

      - layout: left
        title: Master's Degree in Physics
        caption: 2018 - 2020
        sub_title: University of Cagliari
        description: | # this will include new lines to allow paragraphs
            Thesis title: "Large scale simulations of cortical and thalamo-cortical networks of spiking neurons".
      
      - layout: left
        title: Excellence Program of the Master’s Degree in Physics
        caption: 2020
        sub_title: University of Cagliari
        description: | # this will include new lines to allow paragraphs
            An high level academic education program with additional activities.
      
      - layout: left
        title: Summer School
        caption: 2020
        sub_title: Maastricht School of Management
        description: | # this will include new lines to allow paragraphs
            As an activity of the Excellence Program of the Master’s Degree in Physics, I attended the Summer School entitled "Machine Learning and Data Mining with Python".

      - layout: left
        title: Bachelor's Degree in Physics
        caption: 2015 - 2018
        sub_title: University of Cagliari

  - title: Publications # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - Bruno Golosio, Jose Villamar, **Gianmarco Tiddia**, Elena Pastorelli, Jonas Stapmanns, Viviana
        Fanti, Pier Stanislao Paolucci, Abigail Morrison, and Johanna Senk. Runtime construction of
        large-scale spiking neuronal network models on gpu devices. Applied Sciences, volume 13, 2023. [doi](https://doi.org/10.3390/app13179598)
      - **Gianmarco Tiddia**, Bruno Golosio, Viviana Fanti, and Pier Stanislao Paolucci. Simulations
        of working memory spiking networks driven by short-term plasticity. Frontiers in Integrative
        Neuroscience, volume 16, 2022. [doi](https://doi.org/10.3389/fnint.2022.972055)
      - **Gianmarco Tiddia**, Bruno Golosio, Jasper Albers, Johanna Senk, Francesco Simula, Jari
        Pronold, Viviana Fanti, Elena Pastorelli, Pier Stanislao Paolucci, and Sacha J. van Albada.
        Fast simulation of a multi-area spiking network model of macaque cortex on an MPI-GPU cluster.
        Frontiers in Neuroinformatics, volume 16, 2022. [doi](https://doi.org/10.3389/fninf.2022.883333)
      - Bruno Golosio, Chiara De Luca, Cristiano Capone, Elena Pastorelli, Giovanni Stegel, **Gianmarco 
        Tiddia**, Giulia De Bonis, and Pier Stanislao Paolucci. Thalamo-cortical spiking model of
        incremental learning combining perception, context and NREM-sleep. PLOS Computational
        Biology, volume 17, pages 1–26. Public Library of Science, 06 2021. [doi](https://doi.org/10.1371/journal.pcbi.1009045)
      - Bruno Golosio, **Gianmarco Tiddia**, Chiara De Luca, Elena Pastorelli, Francesco Simula, and
        Pier Stanislao Paolucci. Fast Simulations of Highly-Connected Spiking Cortical Models Using
        GPUs. Frontiers in Computational Neuroscience, volume 15, 2021. [doi](https://doi.org/10.3389/fncom.2021.627620)
  
  - title: Preprints # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - **Gianmarco Tiddia**, Luca Sergi, and Bruno Golosio. A theoretical framework for learning 
        through structural plasticity. arXiv:2307.11735 [q-bio.NC] [doi](https://doi.org/10.48550/arXiv.2307.11735)
      - Chiara De Luca, Leonardo Tonielli, Elena Pastorelli, Cristiano Capone, Francesco Simula, 
        Cosimo Lupo, Irene Bernava, Giulia De Bonis, **Gianmarco Tiddia**, Bruno Golosio, and Pier Stanislao Paolucci.
        NREM and REM: cognitive and energetic gains in thalamo-cortical sleeping and awake spiking model.	
        arXiv:2211.06889 [q-bio.NC] [doi](https://doi.org/10.48550/arXiv.2211.06889)

  - title: Work Experience and Academic activities # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: left
        title: ASIMOV prize 2023, member of the Scientific Committee
        caption: 2023
        sub_title: INFN Sezione di Cagliari

      - layout: left
        title: NEST Conference 2023
        caption: 15 June 2023 - 16 June 2023
        description: Partecipation at the NEST Conference (online).

      - layout: left
        title: NEST Conference 2022
        caption: 23 June 2022 - 24 June 2022
        sub_title: Talk
        description: Partecipation at the NEST Conference (online) presenting the talk "MPI parallel simulation of a multi-area spiking network model using NEST GPU".

      - layout: left
        title: BASSES Workshop
        caption: 13 June 2022 - 15 June 2022
        description: Partecipation at the BASSES Workshop in Rome.

      - layout: left
        title: NEST Conference 2021
        caption: 28 June 2021 - 29 June 2021
        description: Partecipation at the NEST Conference (online).

      - layout: left
        title: GIDRM Workshop
        caption: March 2021
        description: Partecipation at the GIDRM Workshop "The promises and Dark Sides
          of Artificial Intelligence in NMR, MRI and Neuroscience" (online). [[Certificate](/certifications/GIDRM2021.pdf)]

      - layout: left
        title: Tutoring
        caption: February 2020 - June 2020
        sub_title: University of Cagliari
        description: Academic advisor in Physics Laboratory Course


  - title: Languages # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - Italian: Mothertongue
      - English: Advanced [[Certificate](https://bestr.it/verify/YAC7SPNATF)]
      - Sardinian: Advanced
  
  - title: Computer skills # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: left
        title: OS
        description: Microsoft Windows (Advanced), Linux (Advanced), MacOS (Intermediate)
      
      - layout: left
        title: Software
        description: ROOT (Intermediate), LabVIEW (Beginner), Microsoft Office suite (Advanced)
        
      - layout: left
        title: Programming
        description: Python (Advanced), Matlab (Advanced), C++ (Intermediate), CUDA (Beginner)
      
      - layout: left
        title: Markup languages
        description: LaTeX (Advanced), Markdown (Advanced), HTML (Beginner)


  #- title: A Little More About Me
  #  layout: text
  #  content: | # this will include new lines to allow paragraphs
  #    Alongside my research interests, some of my other interests and hobbies are:
  #    - LEGO
  #    - Gaming
  #    - Photography
  #    - Mechanical watches
  #    - Fountain pens and inks

  - title: Miscellaneous
    layout: list
    content:
      - layout: left
        title: Driving Licence
        description: European, Class B
    
      


# Footer
# footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
